on:
  schedule:
    - cron: "0 12 * * WED"
  push:
    branches:
      - main
      - master
    path:
      packages.txt
      .github/workflows/render-pkgs.yaml

name: Build packages

jobs:
  render:
    name: Build packages on Ubuntu
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
        with:
          ref: gh-pages
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install remotes
        run: Rscript -e "install.packages('remotes')"
      - name: Install drat.builder 
        run: Rscript -e "remotes::install_github('richfitz/drat.builder')"
      - name: Update DRAT
        run: |
          git config --global user.name "[drat bot]"
          git checkout gh-pages
          Rscript -e "drat.builder::build()"
      - name: Push results
        run: |
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
